name: AWS CodeDeploy Deploy

on:
  push:
    branches:
      - main
env:
  PROJECT_NAME: s-ecs-blue-green-ga
  ENVIRONMENT: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: cache npm dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cdk-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cdk-
            ${{ runner.os }}-

      - name: install dependencies
        run: npm ci
        working-directory: ./cdk

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: output image tag
        id: output-image-tag
        run: |
          # output image tag
          echo "image-tag=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"

      - name: deploy ecr stack
        run: |
          # deploy ecr stack
          npm run cdk -- deploy ${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-ecr \
            -c environment=dev \
            -c projectName=${{ env.PROJECT_NAME }} \
            -c imageTag=${{ steps.output-image-tag.outputs.image-tag }} \
            --require-approval never
        working-directory: ./cdk

      - name: login to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: output ecr repository name
        id: output-repository-name
        run: |
          # output ecr repository name
          repositoryName=$(jq -r '.["${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-ecr"].RepositoryName' outputs.json)
          echo "repository-name=${repositoryName}" >> "$GITHUB_OUTPUT"
        working-directory: ./cdk

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image to Amazon ECR
        uses: docker/build-push-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{  steps.output-repository-name.outputs.repository-name }}
          IMAGE_TAG: ${{ steps.output-image-tag.outputs.image-tag }}
        with:
          context: ./app
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: deploy app stack
        run: |
          # deploy app stack
          npm run cdk -- deploy ${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-app \
            -c environment=dev \
            -c projectName=${{ env.PROJECT_NAME }} \
            -c imageTag=${{ steps.output-image-tag.outputs.image-tag }} \
            --require-approval never
        working-directory: ./cdk

      - name: Generate appspec.yaml
        run: |
          # Generate appspec.yaml
          taskDefinitionArn=$(jq -r '.["${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-app"].EcsTaskDefinitionArn' outputs.json)
          appContainerName=$(jq -r '.["${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-app"].EcsAppContainerName' outputs.json)
          
          cat <<EOF > appspec.yaml
          version: 0.0
          Resources:
            - TargetService:
                Type: AWS::ECS::Service
                Properties:
                  TaskDefinition: ${taskDefinitionArn}
                  LoadBalancerInfo:
                    ContainerName: ${appContainerName}
                    ContainerPort: 3000
          EOF
        working-directory: ./cdk

      - name: deploy app with AWS CodeDeploy
        run: |
          # deploy app with AWS CodeDeploy
          applicationName=$(jq -r '.["${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-app"].CodeDeployApplicationName' outputs.json)
          deploymentConfigName=$(jq -r '.["${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-app"].CodeDeployDeploymentConfigName' outputs.json)
          deploymentGroupName=$(jq -r '.["${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-app"].CodeDeployDeploymentGroupName' outputs.json)
          appspec=$(cat appspec.yaml)
          
          aws deploy create-deployment \
            --application-name "${applicationName}" \
            --deployment-group-name "${deploymentGroupName}" \
            --deployment-config-name "${deploymentConfigName}" \
            --revision revisionType=AppSpecContent,appSpecContent={content="${appspec}"}
        working-directory: ./cdk
